In [47]:
from pandas import json_normalize
import json

#return json object
filename = 'leetcodeProblems.json'
obj = json.load(open(filename))
problem_list = obj['stat_status_pairs']
problem_list[0]

{'stat': {'question_id': 3457,
  'question__article__live': None,
  'question__article__slug': None,
  'question__article__has_video_solution': None,
  'question__title': 'Invalid Tweets II',
  'question__title_slug': 'invalid-tweets-ii',
  'question__hide': False,
  'total_acs': 74,
  'total_submitted': 81,
  'frontend_question_id': 3150,
  'is_new_question': True},
 'status': None,
 'difficulty': {'level': 1},
 'paid_only': True,
 'is_favor': False,
 'frequency': 0,
 'progress': 0}

In [48]:
df = json_normalize(problem_list)
df.head()

,status,paid_only,is_favor,frequency,progress,stat.question_id,stat.question__article__live,stat.question__article__slug,stat.question__article__has_video_solution,stat.question__title,stat.question__title_slug,stat.question__hide,stat.total_acs,stat.total_submitted,stat.frontend_question_id,stat.is_new_question,difficulty.level
0,None,True,False,0,0,3457,None,None,None,Invalid Tweets II,invalid-tweets-ii,False,74,81,3150,True,1
1,None,True,False,0,0,3449,None,None,None,Maximum Hamming Distances,maximum-hamming-distances,False,226,290,3141,True,3
2,None,True,False,0,0,3448,None,None,None,Consecutive Available Seats II,consecutive-available-seats-ii,False,199,305,3140,True,2
3,None,True,False,0,0,3441,None,None,None,Equalize Strings by Adding or Removing Charact...,equalize-strings-by-adding-or-removing-charact...,False,344,583,3135,False,2
4,None,True,False,0,0,3440,None,None,None,Server Utilization Time,server-utilization-time,False,369,867,3126,False,2

In [49]:
df.to_csv('leetcodeProblems.csv', index=False)

In [50]:
free = df[df['paid_only'] == False]
free.head()

free.to_csv('free_leetcodeProblems.csv', index=False)

In [51]:
easy = free[free['difficulty.level'] == 1]
medium = free[free['difficulty.level'] == 2]
hard = free[free['difficulty.level'] == 3]

columns_to_keep = [
    'stat.question_id',
    'stat.frontend_question_id',
    'stat.question__title',
    'stat.question__title_slug',
    'stat.total_acs',
    'stat.total_submitted',
]

easy = easy[columns_to_keep]
medium = medium[columns_to_keep]
hard = hard[columns_to_keep]

In [52]:
easy.to_csv('easy_free_leetcodeProblems.csv', index=False)
medium.to_csv('medium_free_leetcodeProblems.csv', index=False)
hard.to_csv('hard_free_leetcodeProblems.csv', index=False)

In [53]:
easy.head()

,stat.question_id,stat.frontend_question_id,stat.question__title,stat.question__title_slug,stat.total_acs,stat.total_submitted
12,3415,3142,Check if Grid Satisfies Conditions,check-if-grid-satisfies-conditions,21956,55211
13,3412,3146,Permutation Difference between Two Strings,permutation-difference-between-two-strings,25082,28140
17,3408,3120,Count the Number of Special Characters I,count-the-number-of-special-characters-i,36068,55629
27,3398,3127,Make a Square with the Same Color,make-a-square-with-the-same-color,21278,42490
28,3397,3131,Find the Integer Added to Array I,find-the-integer-added-to-array-i,37167,45796

In [54]:


easy = easy[columns_to_keep]
easy.head()

,stat.question_id,stat.frontend_question_id,stat.question__title,stat.question__title_slug,stat.total_acs,stat.total_submitted
12,3415,3142,Check if Grid Satisfies Conditions,check-if-grid-satisfies-conditions,21956,55211
13,3412,3146,Permutation Difference between Two Strings,permutation-difference-between-two-strings,25082,28140
17,3408,3120,Count the Number of Special Characters I,count-the-number-of-special-characters-i,36068,55629
27,3398,3127,Make a Square with the Same Color,make-a-square-with-the-same-color,21278,42490
28,3397,3131,Find the Integer Added to Array I,find-the-integer-added-to-array-i,37167,45796

In [55]:
easy.sample(5)

,stat.question_id,stat.frontend_question_id,stat.question__title,stat.question__title_slug,stat.total_acs,stat.total_submitted
369,2881,2788,Split Strings by Separator,split-strings-by-separator,50380,68363
101,3320,3038,Maximum Number of Operations With the Same Sco...,maximum-number-of-operations-with-the-same-sco...,30492,59330
879,2361,2243,Calculate Digit Sum of a String,calculate-digit-sum-of-a-string,38358,58241
2576,586,586,Customer Placing the Largest Number of Orders,customer-placing-the-largest-number-of-orders,254906,393616
2919,231,231,Power of Two,power-of-two,1304212,2731003

In [56]:
def open_random_problem(df):
    import webbrowser
    problem = df.sample(1)
    slug = problem['stat.question__title_slug'].values[0]
    url = f'https://leetcode.com/problems/{slug}/'
    webbrowser.open(url)

In [46]:
open_random_problem(easy)